// ============================================================
// CLAW4SCIENCE — Project Data
// Source: claw4science.org
// ============================================================

const PROJECTS = [
  // ── CORE PLATFORM ──────────────────────────────────────────
  {
    id: "openclaw",
    name: "OpenClaw",
    category: "core",
    categoryLabel: "Core Platform",
    stars: "328K",
    starsNum: 328000,
    lang: "TypeScript",
    langClass: "lang-typescript",
    badge: null,
    icon: "🦀",
    desc: "The core platform. Personal AI assistant connecting 20+ messaging apps (WhatsApp, Telegram, Slack, Discord, Signal, iMessage, Teams, Matrix, Feishu, LINE). Voice support on macOS/iOS/Android with live Canvas rendering.",
    tags: ["ai-assistant", "multi-platform", "voice", "canvas"],
    links: [{ label: "GitHub", url: "https://github.com/openclaw/openclaw" }]
  },
  {
    id: "nanobot",
    name: "NanoBot",
    category: "core",
    categoryLabel: "Core Platform",
    stars: "35.3K",
    starsNum: 35300,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "🤖",
    desc: "Ultra-lightweight OpenClaw in Python. 99% less code, full agent capabilities. Supports MCP, multi-model (OpenAI, Anthropic, Gemini, Ollama), memory, cron, sub-agents. Install: pip install nanobot-ai.",
    tags: ["lightweight", "multi-model", "MCP", "sub-agents"],
    links: [{ label: "GitHub", url: "https://github.com/HKUDS/nanobot" }]
  },
  {
    id: "zeroclaw",
    name: "ZeroClaw",
    category: "core",
    categoryLabel: "Core Platform",
    stars: "27.9K",
    starsNum: 27900,
    lang: "Rust",
    langClass: "lang-rust",
    badge: null,
    icon: "⚡",
    desc: "Fast, small, and fully autonomous AI assistant infrastructure. Deploy anywhere, swap anything. Written in Rust with extreme performance focus — the infrastructure layer for self-hosted AI agents.",
    tags: ["infrastructure", "autonomous", "deploy-anywhere"],
    links: [{ label: "GitHub", url: "https://github.com/zeroclaw-labs/zeroclaw" }]
  },
  {
    id: "picoclaw",
    name: "PicoClaw",
    category: "core",
    categoryLabel: "Core Platform",
    stars: "25.4K",
    starsNum: 25400,
    lang: "Go",
    langClass: "lang-go",
    badge: null,
    icon: "📦",
    desc: "Tiny, fast, and deployable anywhere. Ultra-efficient AI assistant written in Go by Sipeed. Designed for edge devices and resource-constrained environments. Inspired by NanoBot.",
    tags: ["edge", "IoT", "RISC-V", "tiny"],
    links: [
      { label: "Website", url: "https://picoclaw.io" },
      { label: "GitHub", url: "https://github.com/sipeed/picoclaw" }
    ]
  },
  {
    id: "nemoclaw",
    name: "NemoClaw",
    category: "core",
    categoryLabel: "Core Platform",
    stars: "16K",
    starsNum: 16000,
    lang: "JavaScript",
    langClass: "lang-javascript",
    badge: "new",
    icon: "🟩",
    desc: "NVIDIA official reference stack for running OpenClaw securely inside NVIDIA OpenShell sandbox. Managed inference with Nemotron open-source models. Essential for labs running autonomous agents on GPU servers.",
    tags: ["NVIDIA", "sandbox", "security", "GPU"],
    links: [{ label: "GitHub", url: "https://github.com/NVIDIA/NemoClaw" }]
  },
  {
    id: "hermes-agent",
    name: "Hermes Agent",
    category: "core",
    categoryLabel: "Core Platform",
    stars: "10.5K",
    starsNum: 10500,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "🪄",
    desc: "The self-improving AI agent by Nous Research. Built-in learning loop — creates skills from experience, improves during use, persists knowledge across sessions. Per-model parser adaptation for reliable local model tool calls.",
    tags: ["self-improving", "local-models", "per-model-parser", "learning-loop"],
    links: [{ label: "GitHub", url: "https://github.com/NousResearch/hermes-agent" }]
  },

  // ── TEAM & ORCHESTRATION ──────────────────────────────────
  {
    id: "edict",
    name: "Edict",
    category: "team",
    categoryLabel: "Team & Orchestration",
    stars: "12.8K",
    starsNum: 12800,
    lang: "Python",
    langClass: "lang-python",
    badge: "new",
    icon: "👑",
    desc: "Multi-agent orchestration inspired by China's Imperial Three Departments system. 9 specialized AI agents with real-time dashboard, model config, and full audit trails. You are the Emperor — issue edicts, your AI ministers execute.",
    tags: ["multi-agent", "dashboard", "audit-trail"],
    links: [{ label: "GitHub", url: "https://github.com/cft0808/edict" }]
  },
  {
    id: "clawx",
    name: "ClawX",
    category: "team",
    categoryLabel: "Team & Orchestration",
    stars: "4.9K",
    starsNum: 4900,
    lang: "TypeScript",
    langClass: "lang-typescript",
    badge: null,
    icon: "🖥️",
    desc: "Desktop app providing a graphical interface for OpenClaw AI agents. Turns CLI-based AI orchestration into a visual desktop experience without using the terminal.",
    tags: ["desktop", "GUI", "agent-orchestration", "visual"],
    links: [{ label: "GitHub", url: "https://github.com/ValueCell-ai/ClawX" }]
  },
  {
    id: "metaclaw",
    name: "MetaClaw",
    category: "team",
    categoryLabel: "Team & Orchestration",
    stars: "2.3K",
    starsNum: 2300,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "🔄",
    desc: "Self-learning agent that evolves from every conversation. LoRA-based continual learning + reinforcement learning, no GPU cluster needed. Supports OpenClaw, NanoBot, PicoClaw backends.",
    tags: ["meta-learning", "LoRA", "self-evolving", "RL"],
    links: [
      { label: "GitHub", url: "https://github.com/aiming-lab/MetaClaw" },
      { label: "Paper", url: "https://arxiv.org/abs/2603.17187" }
    ]
  },
  {
    id: "hiclaw",
    name: "HiClaw",
    category: "team",
    categoryLabel: "Team & Orchestration",
    stars: "2.9K",
    starsNum: 2900,
    lang: "Shell",
    langClass: "lang-shell",
    badge: "new",
    icon: "🤝",
    desc: "Collaborative Multi-Agent OS by Alibaba. Transparent, human-in-the-loop task coordination via Matrix rooms. Open-source agent team orchestration for enterprise workflows.",
    tags: ["Alibaba", "multi-agent", "Matrix", "human-in-the-loop"],
    links: [{ label: "GitHub", url: "https://github.com/alibaba/hiclaw" }]
  },
  {
    id: "argusbot",
    name: "ArgusBot",
    category: "team",
    categoryLabel: "Team & Orchestration",
    stars: "247",
    starsNum: 247,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "👁️",
    desc: "24/7 supervisor Agent for Codex CLI and Claude Code CLI. Keeps agents running, reviewing, and planning until the job is actually done. Useful for overnight experiments and long-running analysis tasks.",
    tags: ["supervisor", "24/7", "overnight", "agent-management"],
    links: [{ label: "GitHub", url: "https://github.com/waltstephen/ArgusBot" }]
  },

  // ── MEDICAL & CLINICAL ────────────────────────────────────
  {
    id: "evoscientist",
    name: "EvoScientist",
    category: "medical",
    categoryLabel: "Medical & Clinical",
    stars: "1.4K",
    starsNum: 1400,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "🧬",
    desc: "Self-evolving multi-agent AI research system. 6 sub-agents (plan, research, code, debug, analyze, write) for end-to-end scientific discovery. #1 on DeepResearch Bench II. ICAIS 2025 Best Paper Award.",
    tags: ["AI4Science", "multi-agent", "auto-research", "award-winning"],
    links: [
      { label: "Website", url: "https://EvoScientist.ai" },
      { label: "GitHub", url: "https://github.com/EvoScientist/EvoScientist" },
      { label: "Paper", url: "https://arxiv.org/abs/2603.08127" }
    ]
  },
  {
    id: "medgeclaw",
    name: "MedgeClaw",
    category: "medical",
    categoryLabel: "Medical & Clinical",
    stars: "912",
    starsNum: 912,
    lang: "TeX",
    langClass: "lang-shell",
    badge: null,
    icon: "🏥",
    desc: "AI research assistant for biomedicine built on Claude Code with 140K-Dense scientific skills. Real-time research dashboard, RStudio (:8787), JupyterLab (:8888), and Feishu rich card output.",
    tags: ["biomedicine", "RNA-seq", "drug-discovery", "clinical"],
    links: [{ label: "GitHub", url: "https://github.com/xjtulyc/MedgeClaw" }]
  },
  {
    id: "labclaw",
    name: "LabClaw",
    category: "medical",
    categoryLabel: "Medical & Clinical",
    stars: "827",
    starsNum: 827,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "🔬",
    desc: "Operating layer for LabOS — Stanford-Princeton AI Co-Scientists project. Automated scientific co-discovery workflows for laboratory research.",
    tags: ["Stanford", "Princeton", "lab-automation", "co-discovery"],
    links: [{ label: "GitHub", url: "https://github.com/wu-yc/LabClaw" }]
  },
  {
    id: "stella",
    name: "STELLA",
    category: "medical",
    categoryLabel: "Medical & Clinical",
    stars: "113",
    starsNum: 113,
    lang: "Python",
    langClass: "lang-python",
    badge: "new",
    icon: "⭐",
    desc: "Self-evolving multimodal agent platform for biomedical research. From Princeton/Stanford/UCLA. Published on bioRxiv and arXiv. Live demo at stella-agent.com.",
    tags: ["Princeton", "Stanford", "multimodal", "self-evolving"],
    links: [
      { label: "Website", url: "https://stella-agent.com" },
      { label: "GitHub", url: "https://github.com/zaixizhang/STELLA" },
      { label: "Paper", url: "https://arxiv.org/abs/2507.02004" }
    ]
  },

  // ── BIOINFORMATICS & OMICS ────────────────────────────────
  {
    id: "biomni",
    name: "Biomni",
    category: "bioinformatics",
    categoryLabel: "Bioinformatics & Omics",
    stars: "2.9K",
    starsNum: 2900,
    lang: "Python",
    langClass: "lang-python",
    badge: "new",
    icon: "🔭",
    desc: "General-purpose biomedical AI agent from Stanford SNAP Lab. Broad coverage across biomedical tasks with a unified agent architecture.",
    tags: ["Stanford", "biomedical", "general-purpose", "SNAP-Lab"],
    links: [{ label: "GitHub", url: "https://github.com/snap-stanford/biomni" }]
  },
  {
    id: "clawbio",
    name: "ClawBio",
    category: "bioinformatics",
    categoryLabel: "Bioinformatics & Omics",
    stars: "453",
    starsNum: 453,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "🧪",
    desc: "The first bioinformatics-native AI agent skill library. Local-first, reproducible, built on OpenClaw. Covers genomics, population genetics, and equity-focused bioinformatics workflows.",
    tags: ["bioinformatics", "genomics", "local-first", "reproducible"],
    links: [{ label: "GitHub", url: "https://github.com/ClawBio/ClawBio" }]
  },
  {
    id: "autoba",
    name: "AutoBA",
    category: "bioinformatics",
    categoryLabel: "Bioinformatics & Omics",
    stars: "222",
    starsNum: 222,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "📊",
    desc: "An AI agent for fully automated multi-omic analyses. Supports RNA-seq, scRNA-seq, spatial transcriptomics, WGS/WES, and ChIP-seq with automated code repair.",
    tags: ["multi-omics", "RNA-seq", "spatial-transcriptomics", "self-debugging"],
    links: [
      { label: "GitHub", url: "https://github.com/JoshuaChou2018/AutoBA" },
      { label: "Paper", url: "https://doi.org/10.1038/s41467-024-53454-6" }
    ]
  },
  {
    id: "cellvoyager",
    name: "CellVoyager",
    category: "bioinformatics",
    categoryLabel: "Bioinformatics & Omics",
    stars: "154",
    starsNum: 154,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "🔬",
    desc: "AI CompBio agent that autonomously analyzes biological data and generates new insights. From Stanford Zou Group. Published in Nature Methods. Specializes in scRNA-seq.",
    tags: ["Stanford", "Nature Methods", "scRNA-seq", "autonomous-analysis"],
    links: [
      { label: "GitHub", url: "https://github.com/zou-group/CellVoyager" },
      { label: "Paper", url: "https://www.nature.com/articles/s41592-025-02549-z" }
    ]
  },
  {
    id: "crispr-gpt",
    name: "CRISPR-GPT",
    category: "bioinformatics",
    categoryLabel: "Bioinformatics & Omics",
    stars: "147",
    starsNum: 147,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "✂️",
    desc: "LLM agent for CRISPR genome engineering. Assists with guide RNA design, experiment planning, and protocol optimization.",
    tags: ["CRISPR", "gene-editing", "guide-RNA"],
    links: [{ label: "GitHub", url: "https://github.com/cong-lab/crispr-gpt-pub" }]
  },
  {
    id: "omicsclaw",
    name: "OmicsClaw",
    category: "bioinformatics",
    categoryLabel: "Bioinformatics & Omics",
    stars: "91",
    starsNum: 91,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "🧬",
    desc: "Multi-omics AI analysis tool from TianGz Lab. Focused on genomics, transcriptomics, and proteomics data processing with intelligent agent workflows.",
    tags: ["omics", "genomics", "proteomics", "bioinformatics"],
    links: [{ label: "GitHub", url: "https://github.com/TianGzlab/OmicsClaw" }]
  },
  {
    id: "pantheondos",
    name: "PantheonOS",
    category: "bioinformatics",
    categoryLabel: "Bioinformatics & Omics",
    stars: "336",
    starsNum: 336,
    lang: "Python",
    langClass: "lang-python",
    badge: "new",
    icon: "🗺️",
    desc: "Evolvable, distributed agent framework for data science from the dynamo/Spateo team. Specialized in single-cell and spatial transcriptomics workflows.",
    tags: ["single-cell", "spatial-transcriptomics", "distributed"],
    links: [{ label: "GitHub", url: "https://github.com/aristoteleo/PantheonOS" }]
  },

  // ── DRUG DISCOVERY ────────────────────────────────────────
  {
    id: "chemcrow",
    name: "ChemCrow",
    category: "drug",
    categoryLabel: "Drug Discovery & Molecular",
    stars: "887",
    starsNum: 887,
    lang: "Python",
    langClass: "lang-python",
    badge: "new",
    icon: "⚗️",
    desc: "Pioneering chemistry AI agent (2023) from ur-whitelab. LangChain-based, cited in official docs. The foundational project that inspired MDCrow and the broader science agent movement.",
    tags: ["chemistry", "pioneer", "LangChain"],
    links: [{ label: "GitHub", url: "https://github.com/ur-whitelab/chemcrow-public" }]
  },
  {
    id: "virtual-lab",
    name: "Virtual Lab",
    category: "drug",
    categoryLabel: "Drug Discovery & Molecular",
    stars: "649",
    starsNum: 649,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "🧫",
    desc: "A virtual lab of LLM agents for science research. Multi-agent system for nanobody design with principal investigator agent coordination.",
    tags: ["multi-agent", "nanobody-design", "protein-engineering", "Stanford"],
    links: [{ label: "GitHub", url: "https://github.com/zou-group/virtual-lab" }]
  },
  {
    id: "origene",
    name: "OriGene",
    category: "drug",
    categoryLabel: "Drug Discovery & Molecular",
    stars: "196",
    starsNum: 196,
    lang: "Python",
    langClass: "lang-python",
    badge: "new",
    icon: "💊",
    desc: "Self-evolving virtual disease biologist for mechanism-guided therapeutic target discovery. Automates disease mechanism analysis and drug target identification.",
    tags: ["target-discovery", "disease-mechanism", "self-evolving"],
    links: [{ label: "GitHub", url: "https://github.com/GENTEL-lab/OriGene" }]
  },
  {
    id: "aiagents4pharma",
    name: "AIAgents4Pharma",
    category: "drug",
    categoryLabel: "Drug Discovery & Molecular",
    stars: "71",
    starsNum: 71,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "💉",
    desc: "Multi-agent platform for pharmaceutical R&D. Covers drug discovery, drug development, and clinical pipeline automation. Built by VirtualPatientEngine.",
    tags: ["pharma", "drug-discovery", "LangGraph", "knowledge-graph"],
    links: [{ label: "GitHub", url: "https://github.com/VirtualPatientEngine/AIAgents4Pharma" }]
  },

  // ── AUTONOMOUS RESEARCH ───────────────────────────────────
  {
    id: "autoresearch",
    name: "autoresearch",
    category: "research",
    categoryLabel: "Autonomous Research",
    stars: "60.7K",
    starsNum: 60700,
    lang: "Python",
    langClass: "lang-python",
    badge: "new",
    icon: "🤖",
    desc: "By Andrej Karpathy. Give an AI agent a small LLM training setup and let it experiment autonomously overnight. Single GPU, ~100 experiments/night. Works with Claude Code, Codex, or any agent.",
    tags: ["Karpathy", "autonomous", "LLM-training", "single-GPU"],
    links: [{ label: "GitHub", url: "https://github.com/karpathy/autoresearch" }]
  },
  {
    id: "deepresearch",
    name: "DeepResearch",
    category: "research",
    categoryLabel: "Autonomous Research",
    stars: "18.6K",
    starsNum: 18600,
    lang: "Python",
    langClass: "lang-python",
    badge: "new",
    icon: "🔍",
    desc: "Tongyi Deep Research by Alibaba. Leading open-source deep research agent (30.5B params, 3.3B activated). State-of-the-art on Humanity's Last Exam and BrowseComp benchmarks.",
    tags: ["Alibaba", "Tongyi", "deep-research", "benchmark-SOTA"],
    links: [{ label: "GitHub", url: "https://github.com/Alibaba-NLP/DeepResearch" }]
  },
  {
    id: "rd-agent",
    name: "RD-Agent",
    category: "research",
    categoryLabel: "Autonomous Research",
    stars: "11.9K",
    starsNum: 11900,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "🏭",
    desc: "Microsoft R&D automation platform. AI-driven data and model research — automates hypothesis generation, experiment design, and iterative improvement for industrial and scientific R&D.",
    tags: ["Microsoft", "R&D-automation", "data-driven", "industrial"],
    links: [{ label: "GitHub", url: "https://github.com/microsoft/RD-Agent" }]
  },
  {
    id: "agentlaboratory",
    name: "AgentLaboratory",
    category: "research",
    categoryLabel: "Autonomous Research",
    stars: "5.5K",
    starsNum: 5500,
    lang: "Python",
    langClass: "lang-python",
    badge: "new",
    icon: "🧑‍🔬",
    desc: "End-to-end autonomous research workflow: Literature Review → Experimentation → Report Writing. Specialized LLM agents collaborate via arXiv, HuggingFace, Python, LaTeX. Includes AgentRxiv.",
    tags: ["multi-agent", "end-to-end", "AgentRxiv", "autonomous"],
    links: [{ label: "GitHub", url: "https://github.com/SamuelSchmidgall/AgentLaboratory" }]
  },
  {
    id: "ai-researcher",
    name: "AI-Researcher",
    category: "research",
    categoryLabel: "Autonomous Research",
    stars: "4.9K",
    starsNum: 4900,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "📝",
    desc: "Autonomous scientific innovation system from HKUDS. NeurIPS 2025 paper. End-to-end research automation: literature review, hypothesis generation, experiment design, and paper writing.",
    tags: ["NeurIPS-2025", "autonomous", "paper-writing", "HKUDS"],
    links: [
      { label: "Website", url: "https://novix.science/chat" },
      { label: "GitHub", url: "https://github.com/HKUDS/AI-Researcher" }
    ]
  },
  {
    id: "ai-scientist-v2",
    name: "AI-Scientist-v2",
    category: "research",
    categoryLabel: "Autonomous Research",
    stars: "2.3K",
    starsNum: 2300,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "🔮",
    desc: "Workshop-level automated scientific discovery via agentic tree search. By Sakana AI. Autonomously generates research papers through iterative hypothesis testing and experimentation.",
    tags: ["Sakana-AI", "paper-generation", "agentic-tree-search"],
    links: [{ label: "GitHub", url: "https://github.com/SakanaAI/AI-Scientist-v2" }]
  },
  {
    id: "openresearcher",
    name: "OpenResearcher",
    category: "research",
    categoryLabel: "Autonomous Research",
    stars: "592",
    starsNum: 592,
    lang: "Python",
    langClass: "lang-python",
    badge: "new",
    icon: "🌐",
    desc: "Fully open agentic LLM (30B-A3B) for long-horizon deep research by TIGER-AI-Lab. 54.8% on BrowseComp-Plus, surpassing GPT-4.1, Claude-Opus-4, Gemini-2.5-Pro. Adopted by NVIDIA Nemotron.",
    tags: ["TIGER-AI-Lab", "open-source", "BrowseComp", "NVIDIA-Nemotron"],
    links: [{ label: "GitHub", url: "https://github.com/TIGER-AI-Lab/OpenResearcher" }]
  },

  // ── PERSONAL WORKBENCH ────────────────────────────────────
  {
    id: "aris",
    name: "ARIS",
    category: "workbench",
    categoryLabel: "Personal Workbench",
    stars: "4.7K",
    starsNum: 4700,
    lang: "Python",
    langClass: "lang-python",
    badge: "new",
    icon: "😴",
    desc: "Auto-Research-In-Sleep — let Claude Code do research while you sleep. Lightweight Markdown-only skills for autonomous ML research. Zero dependencies, works with OpenClaw, Codex, or any LLM agent.",
    tags: ["Claude-Code", "sleep-research", "cross-model", "Markdown-skills"],
    links: [{ label: "GitHub", url: "https://github.com/wanshuiyin/Auto-claude-code-research-in-sleep" }]
  },
  {
    id: "dr-claw",
    name: "Dr. Claw",
    category: "workbench",
    categoryLabel: "Personal Workbench",
    stars: "576",
    starsNum: 576,
    lang: "JavaScript",
    langClass: "lang-javascript",
    badge: null,
    icon: "👨‍⚕️",
    desc: "AI Research IDE with built-in 'AI Doctors' assistants. Full research lifecycle: Survey → Ideation → Experiment → Publication → Promotion. 100+ research skills, auto pipeline planning, LaTeX rendering.",
    tags: ["research-IDE", "multi-agent", "LaTeX", "PWA", "full-lifecycle"],
    links: [{ label: "GitHub", url: "https://github.com/OpenLAIR/dr-claw" }]
  },
  {
    id: "scienceclaw-beita",
    name: "ScienceClaw",
    category: "workbench",
    categoryLabel: "Personal Workbench",
    stars: "282",
    starsNum: 282,
    lang: "TypeScript",
    langClass: "lang-typescript",
    badge: null,
    icon: "🎓",
    desc: "Self-evolving AI research colleague. 285 skills that grow at runtime — the agent writes new skills based on your usage patterns. 4-layer persistent memory with LanceDB, 1hr+ session timeout.",
    tags: ["self-evolving", "persistent-memory", "zero-hallucination", "28-disciplines"],
    links: [{ label: "GitHub", url: "https://github.com/beita6969/ScienceClaw" }]
  },
  {
    id: "bioagents",
    name: "BioAgents",
    category: "workbench",
    categoryLabel: "Personal Workbench",
    stars: "114",
    starsNum: 114,
    lang: "TypeScript",
    langClass: "lang-typescript",
    badge: null,
    icon: "🧫",
    desc: "AI scientist framework for autonomous deep research in biological sciences. Multi-agent system combining literature analysis with data scientist agents for iterative scientific discovery.",
    tags: ["biology", "literature-analysis", "data-science", "iterative-discovery"],
    links: [{ label: "GitHub", url: "https://github.com/bio-xyz/BioAgents" }]
  },

  // ── PAPER & LITERATURE ────────────────────────────────────
  {
    id: "autoresearchclaw",
    name: "AutoResearchClaw",
    category: "papers",
    categoryLabel: "Paper & Literature",
    stars: "7.18K",
    starsNum: 7180,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "📄",
    desc: "Fully autonomous, self-evolving research framework: from a one-line idea to a conference-level paper. 23-stage pipeline with multi-agent debate, self-healing error correction, citation verification.",
    tags: ["idea-to-paper", "self-evolving", "23-stage", "citation-verification"],
    links: [{ label: "GitHub", url: "https://github.com/aiming-lab/AutoResearchClaw" }]
  },
  {
    id: "research-claw",
    name: "Research-Claw",
    category: "papers",
    categoryLabel: "Paper & Literature",
    stars: "377",
    starsNum: 377,
    lang: "TypeScript",
    langClass: "lang-typescript",
    badge: null,
    icon: "🗒️",
    desc: "Full-stack AI research assistant — 'In the AI era, why can't everyone be a PI?' Supports extensible skills, literature review, note-taking, experiment tracking, and paper writing end to end. 350+ plugins available.",
    tags: ["full-stack", "PI-for-everyone", "extensible"],
    links: [{ label: "GitHub", url: "https://github.com/wentorai/Research-Claw" }]
  },
  {
    id: "citationclaw",
    name: "CitationClaw",
    category: "papers",
    categoryLabel: "Paper & Literature",
    stars: "202",
    starsNum: 202,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "📚",
    desc: "Turning every citation into explainable impact. Citation analysis and impact assessment tool for academic research — tracks citation networks, measures influence, and provides explainable bibliometric insights.",
    tags: ["citation-analysis", "impact", "explainable"],
    links: [{ label: "GitHub", url: "https://github.com/VisionXLab/CitationClaw" }]
  },
  {
    id: "clawphd",
    name: "ClawPhD",
    category: "papers",
    categoryLabel: "Paper & Literature",
    stars: "138",
    starsNum: 138,
    lang: "Python",
    langClass: "lang-python",
    badge: null,
    icon: "🎓",
    desc: "Agent that turns academic papers into publication-ready diagrams, posters, videos, and more. Visual research communication tool — automates the creation of conference materials from your manuscripts.",
    tags: ["diagrams", "posters", "videos", "visualization"],
    links: [{ label: "GitHub", url: "https://github.com/ZhihaoAIRobotic/ClawPhD" }]
  },

  // ── EDUCATION ─────────────────────────────────────────────
  {
    id: "openmaic",
    name: "OpenMAIC",
    category: "education",
    categoryLabel: "Education",
    stars: "10.6K",
    starsNum: 10600,
    lang: "TypeScript",
    langClass: "lang-typescript",
    badge: null,
    icon: "🏫",
    desc: "Open Multi-Agent Interactive Classroom by Tsinghua University. One-click immersive AI classroom with AI teachers and peers. Slides, quizzes, whiteboard, PBL. Published in JCST'26.",
    tags: ["Tsinghua", "classroom", "multi-agent", "PBL"],
    links: [
      { label: "Website", url: "https://open.maic.chat" },
      { label: "GitHub", url: "https://github.com/THU-MAIC/OpenMAIC" },
      { label: "Paper", url: "https://doi.org/10.1007/s11390-025-6000-0" }
    ]
  },

  // ── BENCHMARKS ────────────────────────────────────────────
  {
    id: "researchclawbench",
    name: "ResearchClawBench",
    category: "benchmark",
    categoryLabel: "Benchmarks",
    stars: "50",
    starsNum: 50,
    lang: "Jupyter Notebook",
    langClass: "lang-python",
    badge: "new",
    icon: "📏",
    desc: "Benchmark for evaluating whether AI agents can independently conduct scientific research. 40 real-science tasks across 10 disciplines, two-stage pipeline (autonomous research + LLM peer-review scoring).",
    tags: ["benchmark", "evaluation", "multi-agent", "scientific-research", "SJTU"],
    links: [
      { label: "GitHub", url: "https://github.com/InternScience/ResearchClawBench" },
      { label: "Paper", url: "https://arxiv.org/abs/2512.16969" }
    ]
  }
];

const CATEGORIES = [
  { id: "all", label: "All Projects", icon: "🌐" },
  { id: "core", label: "Core Platform", icon: "⚙️" },
  { id: "team", label: "Team & Orchestration", icon: "👥" },
  { id: "medical", label: "Medical & Clinical", icon: "🏥" },
  { id: "bioinformatics", label: "Bioinformatics & Omics", icon: "🧬" },
  { id: "drug", label: "Drug Discovery", icon: "💊" },
  { id: "research", label: "Autonomous Research", icon: "🤖" },
  { id: "workbench", label: "Personal Workbench", icon: "🖥️" },
  { id: "papers", label: "Paper & Literature", icon: "📄" },
  { id: "education", label: "Education", icon: "🎓" },
  { id: "benchmark", label: "Benchmarks", icon: "📏" }
];

const WATCHING = [
  { name: "OpenAGS", stars: 43, url: "https://github.com/openags/OpenAGS" },
  { name: "SR-Scientist", stars: 35, url: "https://github.com/GAIR-NLP/SR-Scientist" },
  { name: "OpenLife", stars: 30, url: "https://github.com/AndyZhuang/OpenLife" },
  { name: "GeneClaw", stars: 29, url: "https://github.com/Clawland-AI/Geneclaw" },
  { name: "MatClaw", stars: 26, url: "https://github.com/DingyangLyu/MatClaw" },
  { name: "OmicClaw", stars: 23, url: "https://github.com/Starlitnightly/omicclaw" },
  { name: "FastClaw", stars: 21, url: "https://github.com/fastclaw-ai/fastclaw" },
  { name: "POPGENAGENT", stars: 9, url: "https://github.com/ai4nucleome/POPGENAGENT" },
  { name: "MolClaw", stars: 6, url: "https://github.com/IDEA-XL/MolClaw" },
  { name: "EpiClaw", stars: 4, url: "https://github.com/GBA-BI/EpiClaw" },
  { name: "ChemClaw", stars: 5, url: "https://github.com/AI4Chem/ChemClaw" },
  { name: "CARIBOU", stars: 2, url: "https://github.com/OpenTechBio/CARIBOU" },
  { name: "autoBioResearch", stars: 1, url: "https://github.com/JMGamma/autoBioResearch" },
  { name: "BioOS-Claws", stars: 0, url: "https://github.com/GBA-BI/BioOS-Claws" }
];
